services:
  db:
    image: postgres:17.4
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build: .
    restart: always
    command: /root/.local/bin/uv run python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
#    volumes:
#      - .:/code # Mount the local project directory into the container for development
#    environment:
#      - UV_LINK_MODE=copy # Tell uv to copy instead of hardlink across filesystems